// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using personagens_mvc.data;

#nullable disable

namespace personagens_mvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251113133318_CriarBanco")]
    partial class CriarBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("personagens_mvc.Models.Personagem", b =>
                {
                    b.Property<int>("idPersonagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPersonagem"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("nivel")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPersonagem");

                    b.ToTable("tabelaPersonagem");

                    b.HasDiscriminator<string>("Tipo").HasValue("Personagem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("personagens_mvc.Models.Guerreiro", b =>
                {
                    b.HasBaseType("personagens_mvc.Models.Personagem");

                    b.HasDiscriminator().HasValue("Guerreiro");
                });

            modelBuilder.Entity("personagens_mvc.Models.Mago", b =>
                {
                    b.HasBaseType("personagens_mvc.Models.Personagem");

                    b.HasDiscriminator().HasValue("Mago");
                });
#pragma warning restore 612, 618
        }
    }
}
